plugins {
    id 'com.android.application'
}

android {
    namespace 'mg.appmada.rhayaudiobridge'
    compileSdk 35

    defaultConfig {
        applicationId 'mg.appmada.rhayaudiobridge.compat'
        minSdk 26
        targetSdk 34
        versionCode 2
        versionName '1.1.0-compat'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
